// API contracts come from @tam/shared (type-only, so no validation code reaches the bundle).
export type {
  ApiErrorBody,
  AuthUserDto,
  ChannelDto,
  ChannelStatsDto,
  ChannelStorageLocationDto,
  ChatType,
  ConnectGoogleDriveRequest,
  CreateLocalLocationRequest,
  GoogleDriveConnectDto,
  GoogleDrivePollDto,
  ImportJobChannelDto,
  ImportJobDto,
  ImportJobPhase,
  ImportJobType,
  ImportMode,
  ImportRequest,
  JobStatus,
  LocalFolderDto,
  LocalFolderListDto,
  MediaCategory,
  Page,
  StatsDto,
  StorageCapabilitiesDto,
  StorageCheckDto,
  StorageKind,
  StorageLocationDto,
  StorageLocationListDto,
  StorageSpaceDto,
  UpdateChannelRequest,
  UpdateStorageLocationRequest,
  TelegramAuthenticateRequest,
  TelegramConnectionState,
  TelegramDialogDto,
  TelegramDialogListDto,
  TelegramStatusDto,
  TelegramUserDto,
} from '@tam/shared';

export {
  NETWORK_ERROR_MESSAGE,
  SERVER_ERROR_MESSAGE,
  UNAVAILABLE_ERROR_MESSAGE,
  UNKNOWN_ERROR_MESSAGE,
  detailString,
  isNotFoundError,
  retryAfterSeconds,
  toApiError,
  validationMessage,
  type ApiError,
} from './api-error';
